/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lenovo' at '18-9-6 上午10:43' with Gradle 2.14.1
 *
 * @author lenovo, @date 18-9-6 上午10:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
